# Generated by Django 5.2.8 on 2025-11-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/images/silly cat.jpg', upload_to=['profile_pics']),
        ),
    ]
