# Generated by Django 5.2.8 on 2025-12-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1, verbose_name='Vote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
